### ISSUE TITLE
Update OL3 version in bower.json

### ISSUE THREAD

**Issue by claustres** [tombatossals/angular-openlayers-directive#185]
Following this breaking change https://github.com/tombatossals/angular-openlayers-directive/commit/e664a6a5fc51a999f0d1af8aae33d6743ba06568 I think the bower.json should use 3.8.2 instead of 3.4.0.

In my specific case this breaks otherwise.

**Comment by juristr** [comment]
@claustres Hi, you're right, thx for reminding me. 

The problem with ol3 is that it does not have an official bower repository and I don't have access to the one that has been referenced by the angular-openlayers-directive. Thus, [I created my own (probably the 100th out there) and referenced it](https://github.com/juristr/ol3-bower-dist).
The only downside is that you may have to adjust your paths in your application as the newly referenced ol3 dist repo may have a different path.

There are some tests failing after the update, so I have to adjust them. I'll let you know when done. Meanwhile you should be able to simply install the new ol3 version manually through bower:

```
bower install ol3-bower-dist
```

**Comment by martin-s** [comment]
The question you have to think about: Why do we need two package management tools (npm & bower) for a project? I would like the idea in using just one tool for dependencies. This are also the reasons why OL3 publishes only npm packages.

**Comment by juristr** [comment]
> This is also the reason why OL3 publishes only npm packages.

Yep, and that's exactly what people claim most about.

@martin-s But fair enough. Personally I'd only go for npm (or JSPM) and discard bower. The problem is mostly that the whole package managers ecosystem is structured like it is structured currently. As such people have their established workflows which either favors bower or npm or jspm or whatever. As a library developer you want devs to be able to consume your package as easily as possible and therefore you should (but definitely don't have to) support most of the package managers out there.

But actually that's not a major issue. I'm going to [publish a blog post](http://juristr.com/blog/) on how easy it can be to have automated releases on npm and bower through Travis, even perfectly semantically versioned (without moving your fingers :wink: ).

**Comment by claustres** [comment]
Just switched to https://github.com/tombatossals/ol3-compiled/releases/tag/v3.8.2 in my fork made everything working again. The directive might use whatever repository but it has to reference the right OL3 version otherwise it does not work well and people will not understand the problem easily.

**Comment by juristr** [comment]
I'll fix that tomorrow morning.

**Comment by claustres** [comment]
:+1:

**Comment by juristr** [comment]
@claustres You did use this version, right:

```json
...
"dependencies": {
    "angular": "*",
    "angular-sanitize": "*",
    "openlayers3": "https://github.com/tombatossals/ol3-compiled.git#3.8.2"
  },
...
```

**Comment by claustres** [comment]
Yes : https://github.com/claustres/angular-openlayers-directive/blob/master/bower.json

**Comment by juristr** [comment]
@claustres Ok, released it: https://github.com/tombatossals/angular-openlayers-directive/releases

could you give it a go and let me know?

**Comment by claustres** [comment]
Done a quick test, seems to be OK.
