### ISSUE TITLE
Support for Angular 1.5.8

### ISSUE THREAD

**Issue by lephleg** [tombatossals/angular-openlayers-directive#333]
I'd like to use OpenLayers as part of a new AngularJS application. However my theme is designed based on Angular 1.5.8 which creates a dependency conflict when I try to install angular-openlayers-directive via bower. 

At the moment, it seems that v.1.16 of the directive requires Angular 1.4.9 as a dependency explicitly. I've ignored the bower install warning and kept v1.5.8. However when I tried to implement the quick start example I've received the following error in the console:

> angular.js:13920 **TypeError: Cannot read property 'style' of undefined**
>     at Object.<anonymous> (angular-openlayers-directive.min.js:31)
>     at Object.invoke (angular.js:4718)
>     at Object.enforcedReturnValue [as $get] (angular.js:4557)
>     at Object.invoke (angular.js:4718)
>     at angular.js:4517
>     at getService (angular.js:4664)
>     at injectionArgs (angular.js:4688)
>     at Object.invoke (angular.js:4710)
>     at angular.js:7778
>     at forEach (angular.js:321)(anonymous function) @ angular.js:13920

Would it be possible to extend the support for newer versions of AngularJS like 1.5.x? 
I am also willing to contribute on this, if I'm given an initial guidance.

**Comment by slavede** [comment]
👍  +1

**Comment by slavede** [comment]
Hi, I think this is not because of wrong version of AngularJS, you need to make sure that ol.js is included in your project.

I believe you had the same problem as me (my dev system didn't include ol.js in my index.html).

Try adding ol.js and ol.css inside your index.html and it should work fine.

`<script src="../bower_components/openlayers/ol.js"></script>`

Or, if you have the exact problem as me,

add 

```
  "overrides": {
    "openlayers" : {
      "main": [
        "ol.css",
        "ol.js"
      ]
    }
}
```

to your bower.json and it should start to work
