### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by penrillian-chrisa** [tombatossals/angular-openlayers-directive#84]
Hi, do you have any way of making the map full screen, such that it resizes when the browser window resizes?

**Comment by claustres** [comment]
Adding this to your directive will add a fullscreen button on your map:
```
<openlayers>
    <ol-control name="fullscreen"></ol-control>
</openlayers>
```
But in this case there is no resizing at all because it will occupy all the screen. If you'd like to cover the rendering area of the browser tab then you can try something like this :
```
<openlayers height="100%">
</openlayers>
```
Using either height or width attribute depending if you'd like the map to cover the area in width or height. Indeed, you cannot cover both without stretching the map content (thus have some distortion).

**Comment by juristr** [comment]
I did this as follows:

```html
<div id="map" ng-controller="MapCtrl as map">
  <openlayers ol-center="map.center" ol-defaults="map.mapConfig" custom-layers="true">
    <ol-layer name="{{ layer.name }}" ol-layer-properties="layer" ng-repeat="layer in map.layerManager.getLayers()">
    </ol-layer>
    <ol-marker name="Istanbul"  lat="41.01" lon="28.96" message="Here is Istanbul. Oh my god, such a great city!"></ol-marker>
  </openlayers>
</div>
```

...and in the CSS

```css
#map {
    height: 100%;
    margin: 0;
}
.angular-openlayers-map {
    height: 100%;
    width: 100%;
}
```

Works well.

**Comment by tombatossals** [comment]
Thanks guys, the solutions you provided are perfect.
