### ISSUE TITLE
Layer names

### ISSUE THREAD

**Issue by LewisJared** [tombatossals/angular-openlayers-directive#92]
Layer naming was removed in #77. Was this intentional, as I find this functionality useful!

**Comment by juristr** [comment]
Same here. I already commented on the commit that broke the layer naming: https://github.com/tombatossals/angular-openlayers-directive/commit/d03d438969b82b74a064146415e8e786059e9c99#diff-d782c77869198d8e09129c4109e86ce8

As mentioned there, I have a PR ready to submit which fixes this problem, but I wasn't sure whether this change was intentional. Any feedback would be awesome.
